//! 项目技术栈枚举 —— **生成物，禁止手改**。
//!
//! 由 `crates/mt-ui/tools/gen_tech_icons.mjs` 从它的 CATALOG 生成，与 mt-ui 的徽标
//! 形状表（`crates/mt-ui/src/icons/tech_art.rs`）出自同一张表 —— 种类、落盘字符串、
//! 展示名、菜单分组、徽标五者必须同步，分开手写迟早对不上。改种类请改生成器的
//! CATALOG 后重跑。
//!
//! ⚠ [`ProjectKind::as_str`] 的取值会**落盘**（用户手动指定的类型存进配置的
//! `kindOverride`），已有取值一个字都不能改，否则存量配置读不回来。

use super::TechCategory;

/// 项目技术栈。取值来自生成器 CATALOG，顺序即菜单顺序（按分组聚拢）。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ProjectKind {
    Rust,
    Go,
    Java,
    Kotlin,
    Python,
    CSharp,
    Cpp,
    C,
    Swift,
    Ruby,
    Php,
    Dart,
    Elixir,
    Scala,
    Haskell,
    Zig,
    Lua,
    Perl,
    React,
    Vue,
    Angular,
    Svelte,
    Next,
    Nuxt,
    Astro,
    Solid,
    Remix,
    Vite,
    Node,
    Django,
    Flask,
    FastApi,
    Rails,
    Laravel,
    Spring,
    DotNet,
    Nest,
    Express,
    Deno,
    Bun,
    Flutter,
    Android,
    Apple,
    Tauri,
    Electron,
    Unity,
    Godot,
    Docker,
    Kubernetes,
    Terraform,
    Ansible,
}

impl ProjectKind {
    /// **会落盘**的字符串（配置里的 `kindOverride`）。改一个字就读不回存量配置。
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Go => "go",
            Self::Java => "java",
            Self::Kotlin => "kotlin",
            Self::Python => "python",
            Self::CSharp => "csharp",
            Self::Cpp => "cpp",
            Self::C => "c",
            Self::Swift => "swift",
            Self::Ruby => "ruby",
            Self::Php => "php",
            Self::Dart => "dart",
            Self::Elixir => "elixir",
            Self::Scala => "scala",
            Self::Haskell => "haskell",
            Self::Zig => "zig",
            Self::Lua => "lua",
            Self::Perl => "perl",
            Self::React => "react",
            Self::Vue => "vuejs",
            Self::Angular => "angular",
            Self::Svelte => "svelte",
            Self::Next => "nextjs",
            Self::Nuxt => "nuxtjs",
            Self::Astro => "astro",
            Self::Solid => "solidjs",
            Self::Remix => "remix",
            Self::Vite => "vite",
            Self::Node => "nodejs",
            Self::Django => "django",
            Self::Flask => "flask",
            Self::FastApi => "fastapi",
            Self::Rails => "rails",
            Self::Laravel => "laravel",
            Self::Spring => "spring",
            Self::DotNet => "dotnet",
            Self::Nest => "nestjs",
            Self::Express => "express",
            Self::Deno => "deno",
            Self::Bun => "bun",
            Self::Flutter => "flutter",
            Self::Android => "android",
            Self::Apple => "apple",
            Self::Tauri => "tauri",
            Self::Electron => "electron",
            Self::Unity => "unity",
            Self::Godot => "godot",
            Self::Docker => "docker",
            Self::Kubernetes => "kubernetes",
            Self::Terraform => "terraform",
            Self::Ansible => "ansible",
        }
    }

    // 与 `mt_app::tree::PaneStatus::from_str` 取同一个命名（返回 Option 而非 Result，
    // 失败没有可报的错误细节），不实现 `FromStr` trait
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Self> {
        Some(match s {
            "rust" => Self::Rust,
            "go" => Self::Go,
            "java" => Self::Java,
            "kotlin" => Self::Kotlin,
            "python" => Self::Python,
            "csharp" => Self::CSharp,
            "cpp" => Self::Cpp,
            "c" => Self::C,
            "swift" => Self::Swift,
            "ruby" => Self::Ruby,
            "php" => Self::Php,
            "dart" => Self::Dart,
            "elixir" => Self::Elixir,
            "scala" => Self::Scala,
            "haskell" => Self::Haskell,
            "zig" => Self::Zig,
            "lua" => Self::Lua,
            "perl" => Self::Perl,
            "react" => Self::React,
            "vuejs" => Self::Vue,
            "angular" => Self::Angular,
            "svelte" => Self::Svelte,
            "nextjs" => Self::Next,
            "nuxtjs" => Self::Nuxt,
            "astro" => Self::Astro,
            "solidjs" => Self::Solid,
            "remix" => Self::Remix,
            "vite" => Self::Vite,
            "nodejs" => Self::Node,
            "django" => Self::Django,
            "flask" => Self::Flask,
            "fastapi" => Self::FastApi,
            "rails" => Self::Rails,
            "laravel" => Self::Laravel,
            "spring" => Self::Spring,
            "dotnet" => Self::DotNet,
            "nestjs" => Self::Nest,
            "express" => Self::Express,
            "deno" => Self::Deno,
            "bun" => Self::Bun,
            "flutter" => Self::Flutter,
            "android" => Self::Android,
            "apple" => Self::Apple,
            "tauri" => Self::Tauri,
            "electron" => Self::Electron,
            "unity" => Self::Unity,
            "godot" => Self::Godot,
            "docker" => Self::Docker,
            "kubernetes" => Self::Kubernetes,
            "terraform" => Self::Terraform,
            "ansible" => Self::Ansible,
            _ => return None,
        })
    }

    /// 展示名。专有名词，不进 i18n。
    pub fn label(self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::Go => "Go",
            Self::Java => "Java",
            Self::Kotlin => "Kotlin",
            Self::Python => "Python",
            Self::CSharp => "C#",
            Self::Cpp => "C++",
            Self::C => "C",
            Self::Swift => "Swift",
            Self::Ruby => "Ruby",
            Self::Php => "PHP",
            Self::Dart => "Dart",
            Self::Elixir => "Elixir",
            Self::Scala => "Scala",
            Self::Haskell => "Haskell",
            Self::Zig => "Zig",
            Self::Lua => "Lua",
            Self::Perl => "Perl",
            Self::React => "React",
            Self::Vue => "Vue",
            Self::Angular => "Angular",
            Self::Svelte => "Svelte",
            Self::Next => "Next.js",
            Self::Nuxt => "Nuxt",
            Self::Astro => "Astro",
            Self::Solid => "Solid",
            Self::Remix => "Remix",
            Self::Vite => "Vite",
            Self::Node => "Node.js",
            Self::Django => "Django",
            Self::Flask => "Flask",
            Self::FastApi => "FastAPI",
            Self::Rails => "Ruby on Rails",
            Self::Laravel => "Laravel",
            Self::Spring => "Spring",
            Self::DotNet => ".NET",
            Self::Nest => "NestJS",
            Self::Express => "Express",
            Self::Deno => "Deno",
            Self::Bun => "Bun",
            Self::Flutter => "Flutter",
            Self::Android => "Android",
            Self::Apple => "iOS / macOS",
            Self::Tauri => "Tauri",
            Self::Electron => "Electron",
            Self::Unity => "Unity",
            Self::Godot => "Godot",
            Self::Docker => "Docker",
            Self::Kubernetes => "Kubernetes",
            Self::Terraform => "Terraform",
            Self::Ansible => "Ansible",
        }
    }

    /// 菜单里归到哪个二级分组。
    pub fn category(self) -> TechCategory {
        match self {
            Self::Rust => TechCategory::Language,
            Self::Go => TechCategory::Language,
            Self::Java => TechCategory::Language,
            Self::Kotlin => TechCategory::Language,
            Self::Python => TechCategory::Language,
            Self::CSharp => TechCategory::Language,
            Self::Cpp => TechCategory::Language,
            Self::C => TechCategory::Language,
            Self::Swift => TechCategory::Language,
            Self::Ruby => TechCategory::Language,
            Self::Php => TechCategory::Language,
            Self::Dart => TechCategory::Language,
            Self::Elixir => TechCategory::Language,
            Self::Scala => TechCategory::Language,
            Self::Haskell => TechCategory::Language,
            Self::Zig => TechCategory::Language,
            Self::Lua => TechCategory::Language,
            Self::Perl => TechCategory::Language,
            Self::React => TechCategory::Frontend,
            Self::Vue => TechCategory::Frontend,
            Self::Angular => TechCategory::Frontend,
            Self::Svelte => TechCategory::Frontend,
            Self::Next => TechCategory::Frontend,
            Self::Nuxt => TechCategory::Frontend,
            Self::Astro => TechCategory::Frontend,
            Self::Solid => TechCategory::Frontend,
            Self::Remix => TechCategory::Frontend,
            Self::Vite => TechCategory::Frontend,
            Self::Node => TechCategory::Frontend,
            Self::Django => TechCategory::Backend,
            Self::Flask => TechCategory::Backend,
            Self::FastApi => TechCategory::Backend,
            Self::Rails => TechCategory::Backend,
            Self::Laravel => TechCategory::Backend,
            Self::Spring => TechCategory::Backend,
            Self::DotNet => TechCategory::Backend,
            Self::Nest => TechCategory::Backend,
            Self::Express => TechCategory::Backend,
            Self::Deno => TechCategory::Backend,
            Self::Bun => TechCategory::Backend,
            Self::Flutter => TechCategory::Mobile,
            Self::Android => TechCategory::Mobile,
            Self::Apple => TechCategory::Mobile,
            Self::Tauri => TechCategory::Mobile,
            Self::Electron => TechCategory::Mobile,
            Self::Unity => TechCategory::Mobile,
            Self::Godot => TechCategory::Mobile,
            Self::Docker => TechCategory::Infra,
            Self::Kubernetes => TechCategory::Infra,
            Self::Terraform => TechCategory::Infra,
            Self::Ansible => TechCategory::Infra,
        }
    }
}

/// 全部种类，**已按分组聚拢**：菜单直接按这个顺序分段即可。
pub const ALL_PROJECT_KINDS: &[ProjectKind] = &[
    ProjectKind::Rust,
    ProjectKind::Go,
    ProjectKind::Java,
    ProjectKind::Kotlin,
    ProjectKind::Python,
    ProjectKind::CSharp,
    ProjectKind::Cpp,
    ProjectKind::C,
    ProjectKind::Swift,
    ProjectKind::Ruby,
    ProjectKind::Php,
    ProjectKind::Dart,
    ProjectKind::Elixir,
    ProjectKind::Scala,
    ProjectKind::Haskell,
    ProjectKind::Zig,
    ProjectKind::Lua,
    ProjectKind::Perl,
    ProjectKind::React,
    ProjectKind::Vue,
    ProjectKind::Angular,
    ProjectKind::Svelte,
    ProjectKind::Next,
    ProjectKind::Nuxt,
    ProjectKind::Astro,
    ProjectKind::Solid,
    ProjectKind::Remix,
    ProjectKind::Vite,
    ProjectKind::Node,
    ProjectKind::Django,
    ProjectKind::Flask,
    ProjectKind::FastApi,
    ProjectKind::Rails,
    ProjectKind::Laravel,
    ProjectKind::Spring,
    ProjectKind::DotNet,
    ProjectKind::Nest,
    ProjectKind::Express,
    ProjectKind::Deno,
    ProjectKind::Bun,
    ProjectKind::Flutter,
    ProjectKind::Android,
    ProjectKind::Apple,
    ProjectKind::Tauri,
    ProjectKind::Electron,
    ProjectKind::Unity,
    ProjectKind::Godot,
    ProjectKind::Docker,
    ProjectKind::Kubernetes,
    ProjectKind::Terraform,
    ProjectKind::Ansible,
];
